version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11-alpine
    image: julianmedwards/flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000

  redis:
    image: redis:alpine